### ISSUE TITLE
Missing hooks

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/inlineHtmlGalley#4]
This plugin is missing a couple of hooks that are present in core:

`Templates::Article::Main`
https://github.com/pkp/ojs/blob/1e9f361cd93a7476b36be05124d06a629e028c90/templates/frontend/objects/article_details.tpl#L175

`Templates::Article::Details`
https://github.com/pkp/ojs/blob/1e9f361cd93a7476b36be05124d06a629e028c90/templates/frontend/objects/article_details.tpl#L472

These should be represented in our .tpl files in this plugin.

`Templates::Article::Main` probably goes below the authors in displayInline.tpl.

`Templates::Article::Details` doesn't have as clear a parallel, but could be a dedicated block of "Other Details" made available.

**Comment by ctgraham** [comment]
@wopsononock , is this fully resolved by https://github.com/ulsdevteam/inlineHtmlGalley/pull/5 ?

**Comment by wopsononock** [comment]
Yes, I think so.  In addition to the more extensive changes required to set up the details block, I added the missing hook for Article::Main in displayInline.tpl.
